/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as ContactsRouteImport } from './routes/contacts'
import { Route as BillingRouteImport } from './routes/billing'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AnalyticsRouteImport } from './routes/analytics'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProfileIndexRouteImport } from './routes/profile.index'
import { Route as UIdRouteImport } from './routes/u.$id'
import { Route as ProfileEditRouteImport } from './routes/profile.edit'
import { Route as AdminUsersRouteImport } from './routes/admin.users'
import { Route as AdminTemplatesRouteImport } from './routes/admin.templates'
import { Route as AdminTeamsRouteImport } from './routes/admin.teams'
import { Route as AdminSubscriptionsRouteImport } from './routes/admin.subscriptions'
import { Route as AdminOrgContactsRouteImport } from './routes/admin.org-contacts'
import { Route as AdminOrgAnalyticsRouteImport } from './routes/admin.org-analytics'
import { Route as AdminMyUsersRouteImport } from './routes/admin.my-users'
import { Route as AdminMyGroupRouteImport } from './routes/admin.my-group'
import { Route as AdminGroupsRouteImport } from './routes/admin.groups'
import { Route as AdminAnalyticsRouteImport } from './routes/admin.analytics'

const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactsRoute = ContactsRouteImport.update({
  id: '/contacts',
  path: '/contacts',
  getParentRoute: () => rootRouteImport,
} as any)
const BillingRoute = BillingRouteImport.update({
  id: '/billing',
  path: '/billing',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalyticsRoute = AnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileIndexRoute = ProfileIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ProfileRoute,
} as any)
const UIdRoute = UIdRouteImport.update({
  id: '/u/$id',
  path: '/u/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileEditRoute = ProfileEditRouteImport.update({
  id: '/edit',
  path: '/edit',
  getParentRoute: () => ProfileRoute,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AdminRoute,
} as any)
const AdminTemplatesRoute = AdminTemplatesRouteImport.update({
  id: '/templates',
  path: '/templates',
  getParentRoute: () => AdminRoute,
} as any)
const AdminTeamsRoute = AdminTeamsRouteImport.update({
  id: '/teams',
  path: '/teams',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSubscriptionsRoute = AdminSubscriptionsRouteImport.update({
  id: '/subscriptions',
  path: '/subscriptions',
  getParentRoute: () => AdminRoute,
} as any)
const AdminOrgContactsRoute = AdminOrgContactsRouteImport.update({
  id: '/org-contacts',
  path: '/org-contacts',
  getParentRoute: () => AdminRoute,
} as any)
const AdminOrgAnalyticsRoute = AdminOrgAnalyticsRouteImport.update({
  id: '/org-analytics',
  path: '/org-analytics',
  getParentRoute: () => AdminRoute,
} as any)
const AdminMyUsersRoute = AdminMyUsersRouteImport.update({
  id: '/my-users',
  path: '/my-users',
  getParentRoute: () => AdminRoute,
} as any)
const AdminMyGroupRoute = AdminMyGroupRouteImport.update({
  id: '/my-group',
  path: '/my-group',
  getParentRoute: () => AdminRoute,
} as any)
const AdminGroupsRoute = AdminGroupsRouteImport.update({
  id: '/groups',
  path: '/groups',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAnalyticsRoute = AdminAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => AdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/analytics': typeof AnalyticsRoute
  '/auth': typeof AuthRoute
  '/billing': typeof BillingRoute
  '/contacts': typeof ContactsRoute
  '/privacy': typeof PrivacyRoute
  '/profile': typeof ProfileRouteWithChildren
  '/settings': typeof SettingsRoute
  '/terms': typeof TermsRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/groups': typeof AdminGroupsRoute
  '/admin/my-group': typeof AdminMyGroupRoute
  '/admin/my-users': typeof AdminMyUsersRoute
  '/admin/org-analytics': typeof AdminOrgAnalyticsRoute
  '/admin/org-contacts': typeof AdminOrgContactsRoute
  '/admin/subscriptions': typeof AdminSubscriptionsRoute
  '/admin/teams': typeof AdminTeamsRoute
  '/admin/templates': typeof AdminTemplatesRoute
  '/admin/users': typeof AdminUsersRoute
  '/profile/edit': typeof ProfileEditRoute
  '/u/$id': typeof UIdRoute
  '/profile/': typeof ProfileIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/analytics': typeof AnalyticsRoute
  '/auth': typeof AuthRoute
  '/billing': typeof BillingRoute
  '/contacts': typeof ContactsRoute
  '/privacy': typeof PrivacyRoute
  '/settings': typeof SettingsRoute
  '/terms': typeof TermsRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/groups': typeof AdminGroupsRoute
  '/admin/my-group': typeof AdminMyGroupRoute
  '/admin/my-users': typeof AdminMyUsersRoute
  '/admin/org-analytics': typeof AdminOrgAnalyticsRoute
  '/admin/org-contacts': typeof AdminOrgContactsRoute
  '/admin/subscriptions': typeof AdminSubscriptionsRoute
  '/admin/teams': typeof AdminTeamsRoute
  '/admin/templates': typeof AdminTemplatesRoute
  '/admin/users': typeof AdminUsersRoute
  '/profile/edit': typeof ProfileEditRoute
  '/u/$id': typeof UIdRoute
  '/profile': typeof ProfileIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/analytics': typeof AnalyticsRoute
  '/auth': typeof AuthRoute
  '/billing': typeof BillingRoute
  '/contacts': typeof ContactsRoute
  '/privacy': typeof PrivacyRoute
  '/profile': typeof ProfileRouteWithChildren
  '/settings': typeof SettingsRoute
  '/terms': typeof TermsRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/groups': typeof AdminGroupsRoute
  '/admin/my-group': typeof AdminMyGroupRoute
  '/admin/my-users': typeof AdminMyUsersRoute
  '/admin/org-analytics': typeof AdminOrgAnalyticsRoute
  '/admin/org-contacts': typeof AdminOrgContactsRoute
  '/admin/subscriptions': typeof AdminSubscriptionsRoute
  '/admin/teams': typeof AdminTeamsRoute
  '/admin/templates': typeof AdminTemplatesRoute
  '/admin/users': typeof AdminUsersRoute
  '/profile/edit': typeof ProfileEditRoute
  '/u/$id': typeof UIdRoute
  '/profile/': typeof ProfileIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/analytics'
    | '/auth'
    | '/billing'
    | '/contacts'
    | '/privacy'
    | '/profile'
    | '/settings'
    | '/terms'
    | '/admin/analytics'
    | '/admin/groups'
    | '/admin/my-group'
    | '/admin/my-users'
    | '/admin/org-analytics'
    | '/admin/org-contacts'
    | '/admin/subscriptions'
    | '/admin/teams'
    | '/admin/templates'
    | '/admin/users'
    | '/profile/edit'
    | '/u/$id'
    | '/profile/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/analytics'
    | '/auth'
    | '/billing'
    | '/contacts'
    | '/privacy'
    | '/settings'
    | '/terms'
    | '/admin/analytics'
    | '/admin/groups'
    | '/admin/my-group'
    | '/admin/my-users'
    | '/admin/org-analytics'
    | '/admin/org-contacts'
    | '/admin/subscriptions'
    | '/admin/teams'
    | '/admin/templates'
    | '/admin/users'
    | '/profile/edit'
    | '/u/$id'
    | '/profile'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/analytics'
    | '/auth'
    | '/billing'
    | '/contacts'
    | '/privacy'
    | '/profile'
    | '/settings'
    | '/terms'
    | '/admin/analytics'
    | '/admin/groups'
    | '/admin/my-group'
    | '/admin/my-users'
    | '/admin/org-analytics'
    | '/admin/org-contacts'
    | '/admin/subscriptions'
    | '/admin/teams'
    | '/admin/templates'
    | '/admin/users'
    | '/profile/edit'
    | '/u/$id'
    | '/profile/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  AnalyticsRoute: typeof AnalyticsRoute
  AuthRoute: typeof AuthRoute
  BillingRoute: typeof BillingRoute
  ContactsRoute: typeof ContactsRoute
  PrivacyRoute: typeof PrivacyRoute
  ProfileRoute: typeof ProfileRouteWithChildren
  SettingsRoute: typeof SettingsRoute
  TermsRoute: typeof TermsRoute
  UIdRoute: typeof UIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contacts': {
      id: '/contacts'
      path: '/contacts'
      fullPath: '/contacts'
      preLoaderRoute: typeof ContactsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/billing': {
      id: '/billing'
      path: '/billing'
      fullPath: '/billing'
      preLoaderRoute: typeof BillingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analytics': {
      id: '/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile/': {
      id: '/profile/'
      path: '/'
      fullPath: '/profile/'
      preLoaderRoute: typeof ProfileIndexRouteImport
      parentRoute: typeof ProfileRoute
    }
    '/u/$id': {
      id: '/u/$id'
      path: '/u/$id'
      fullPath: '/u/$id'
      preLoaderRoute: typeof UIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile/edit': {
      id: '/profile/edit'
      path: '/edit'
      fullPath: '/profile/edit'
      preLoaderRoute: typeof ProfileEditRouteImport
      parentRoute: typeof ProfileRoute
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/templates': {
      id: '/admin/templates'
      path: '/templates'
      fullPath: '/admin/templates'
      preLoaderRoute: typeof AdminTemplatesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/teams': {
      id: '/admin/teams'
      path: '/teams'
      fullPath: '/admin/teams'
      preLoaderRoute: typeof AdminTeamsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/subscriptions': {
      id: '/admin/subscriptions'
      path: '/subscriptions'
      fullPath: '/admin/subscriptions'
      preLoaderRoute: typeof AdminSubscriptionsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/org-contacts': {
      id: '/admin/org-contacts'
      path: '/org-contacts'
      fullPath: '/admin/org-contacts'
      preLoaderRoute: typeof AdminOrgContactsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/org-analytics': {
      id: '/admin/org-analytics'
      path: '/org-analytics'
      fullPath: '/admin/org-analytics'
      preLoaderRoute: typeof AdminOrgAnalyticsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/my-users': {
      id: '/admin/my-users'
      path: '/my-users'
      fullPath: '/admin/my-users'
      preLoaderRoute: typeof AdminMyUsersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/my-group': {
      id: '/admin/my-group'
      path: '/my-group'
      fullPath: '/admin/my-group'
      preLoaderRoute: typeof AdminMyGroupRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/groups': {
      id: '/admin/groups'
      path: '/groups'
      fullPath: '/admin/groups'
      preLoaderRoute: typeof AdminGroupsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/analytics': {
      id: '/admin/analytics'
      path: '/analytics'
      fullPath: '/admin/analytics'
      preLoaderRoute: typeof AdminAnalyticsRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminAnalyticsRoute: typeof AdminAnalyticsRoute
  AdminGroupsRoute: typeof AdminGroupsRoute
  AdminMyGroupRoute: typeof AdminMyGroupRoute
  AdminMyUsersRoute: typeof AdminMyUsersRoute
  AdminOrgAnalyticsRoute: typeof AdminOrgAnalyticsRoute
  AdminOrgContactsRoute: typeof AdminOrgContactsRoute
  AdminSubscriptionsRoute: typeof AdminSubscriptionsRoute
  AdminTeamsRoute: typeof AdminTeamsRoute
  AdminTemplatesRoute: typeof AdminTemplatesRoute
  AdminUsersRoute: typeof AdminUsersRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAnalyticsRoute: AdminAnalyticsRoute,
  AdminGroupsRoute: AdminGroupsRoute,
  AdminMyGroupRoute: AdminMyGroupRoute,
  AdminMyUsersRoute: AdminMyUsersRoute,
  AdminOrgAnalyticsRoute: AdminOrgAnalyticsRoute,
  AdminOrgContactsRoute: AdminOrgContactsRoute,
  AdminSubscriptionsRoute: AdminSubscriptionsRoute,
  AdminTeamsRoute: AdminTeamsRoute,
  AdminTemplatesRoute: AdminTemplatesRoute,
  AdminUsersRoute: AdminUsersRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface ProfileRouteChildren {
  ProfileEditRoute: typeof ProfileEditRoute
  ProfileIndexRoute: typeof ProfileIndexRoute
}

const ProfileRouteChildren: ProfileRouteChildren = {
  ProfileEditRoute: ProfileEditRoute,
  ProfileIndexRoute: ProfileIndexRoute,
}

const ProfileRouteWithChildren =
  ProfileRoute._addFileChildren(ProfileRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  AnalyticsRoute: AnalyticsRoute,
  AuthRoute: AuthRoute,
  BillingRoute: BillingRoute,
  ContactsRoute: ContactsRoute,
  PrivacyRoute: PrivacyRoute,
  ProfileRoute: ProfileRouteWithChildren,
  SettingsRoute: SettingsRoute,
  TermsRoute: TermsRoute,
  UIdRoute: UIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
